apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backingservices.app.example.org
spec:
  group: app.example.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                binding:
                  type: object
                  properties:
                    name:
                      type: string
  scope: Namespaced
  names:
    plural: backingservices
    kind: BackingService
