apiVersion: binding.x-k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: sb
spec:
  application:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  service:
    apiVersion: app.example.org/v1alpha1
    kind: BackingService
    name: back1
